export const carslist = [
  {
    title: 'BADA DOST i4',
    img: require('../img/Ashok-Leyland-Bada-Dost-i4.webp'),
    to: '/bada-dost-i4-on-road-price-in-hyderabad',
    payload: '1400 kg',
    gvw: '3490',
    power: '80',
    engine: '1478',
  },

  {
    title: 'BADA DOST i3+',
    img: require('../img/Ashok-Leyland-Bada-Dost-i3-Specifications.webp'),
    to: '/bada-dost-i3-on-road-price-in-hyderabad',
    payload: '1400 kg',
    gvw: '2990',
    power: '80',
    engine: '1478',
  },
  {
    title: 'BADA DOST i3',
    img: require('../img/Ashok-Leyland-Bada-Dost-i3-Specifications.webp'),
    to: '/bada-dost-i3-on-road-price-in-hyderabad',
    payload: '1400 kg',
    gvw: '2990',
    power: '80',
    engine: '1478',
  },
  {
    title: 'BADA DOST +',
    img: require('../img/Ashok-Leyland-Dost-Plus-Price-in-Hyderabad.webp'),
    to: '/dost-plus-on-road-price-in-hyderabad',
    payload: '1500 kg',
    gvw: '2805',
    power: '80',
    engine: '1478',
  },
  {
    title: 'New DOST STRONG',
    img: require('../img/Ashok-Leyland-Dost-Strong-Features.webp'),
    to: '/dost-strong-on-road-price-in-hyderabad',
    payload: '1250 kg',
    gvw: '2590',
    power: '70',
    engine: '1478',
  },
  {
    title: 'DOST LiTE',
    img: require('../img/ashok-leyland-dost-lite.webp'),
    to: '/dost-lite-on-road-price-in-hyderabad',
    payload: '1250 kg',
    gvw: '2545',
    power: '50',
    engine: '1478',
  },
  {
    title: 'DOST CNG',
    img: require('../img/Ashok-Leyland-Dost-CNG-Price-in-Hyderabad.webp'),
    to: '/dost-cng-on-road-price-in-hyderabad',
    payload: '1215 kg',
    gvw: '2545',
    power: '45',
    engine: '1478',
  },
  {
    title: 'PARTNER',
    img: require('../img/Ashok-Leyland-Partner-Features-Specifications-and-Safety.webp'),
    to: '/partner-commercial-truck-on-road-price-in-hyderabad',
    payload: '4579 kg',
    gvw: '7490',
    power: '140',
    engine: '2953',
  },
  {
    title: 'MiTR SCHOOL BUS',
    img: require('../img/Ashok-Leyland-MiTR-School-Bus-Features-Specifications.webp'),
    to: '/mitr-school-bus-on-road-price-in-hyderabad',
    payload: '3700 mm',
    gvw: '6650',
    power: '140',
    engine: '2953',
  },
  {
    title: 'MiTR Staff',
    img: require('../img/Ashok-Leyland-MiTR-Staff-Bus-Specifications-Features-and-Safety.webp'),
    to: '/mitr-staff-bus-on-road-price-in-hyderabad',
    payload: '3700 mm',
    gvw: '6650',
    power: '140',
    engine: '2953',
  },
];
